version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PYTHONUNBUFFERED=1
