[project]
name = "zeno-data-analytics"
version = "0.1.0"
description = "Data analytics app for Zeno"
requires-python = ">=3.12"
dependencies = [
    "boto3",
    "coiled",
    "dask[array,dataframe,distributed,diagnostics]",
    "fastparquet",
    "flox",
    "fsspec",
    "numba>=0.61.2",
    "numbagg",
    "numpy",
    "pandas",
    "prefect",
    "rasterio==1.4.3",
    "rioxarray",
    "s3fs",
    "sparse",
    "xarray",
    "zarr",
    "duckdb",
    "shapely"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pipelines"]

[tool.uv.workspace]
members = [
    "project-zeno-data-infra",
]
