[project]
name = "zeno-data-analytics"
version = "0.1.0"
description = "Data analytics app for Zeno"
requires-python = ">=3.12"
dependencies = [
    "boto3",
    "coiled",
    "dask",
    "fastparquet",
    "flox",
    "fsspec",
    "numpy",
    "pandas",
    "prefect",
    "rioxarray",
    "s3fs",
    "sparse",
    "xarray"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"