from .land_cover_change import create as create_land_cover_change
from .land_cover_composition import create as create_land_cover_composition

api_doc = """
    # Primary Dataset
    | Dataset Key Aspects | Detailed Description |
    |---------------------|----------------------|
    | **Title** | Global land cover |
    | **Description** <br> A descriptive summary of what the dataset is and key details, such as information on geographic coverage, temporal range, and the data sources used. | This Global Land Cover dataset is a combination of two global datasets: the GLAD Land Cover and Land Use Change annual data and the Global Pasture Watch Grassland Class Collection 2 Cultivated Grasslands annual data. This combination is annual from 2015 through 2024. This dataset shows land covers and uses including bare ground and sparse vegetation, short vegetation, tree cover, wetlands, water, snow/ice, cropland, cultivated grasslands, and built-up land. |
    | **Function / usage notes** <br> The intended use of the dataset. How might users employ this data in order to have some impact in the world? | This Global Land Cover dataset is intended to be used for monitoring land cover in individual years as well as change over time. Note that changes over time indicate land cover changes and may or may not capture land use changes.<br>This dataset should be used when a user asks about area in a specific year or gain or loss of area between years for bare ground and sparse vegetation, short vegetation, wetlands, water, snow/ice, cropland, cultivated grasslands, and built-up land. Gain of tree cover can be derived from this dataset. Never use this dataset for tree cover loss, instead refer to the Tree Cover Loss (Hansen/UMD/GLAD) data. This dataset may be overlaid with DIST alert data to find alerts in specific land covers. It can also be used to find where land cover has changed since 2020 and then overlaid with the Natural Lands map to identify land cover changes on land that was natural in 2020.<br>Any questions about snapshot or baseline land cover in a given year, any questions about change over time in land cover in a single time step or trends over the full time period. Any questions about a transition matrix of classes – what class became what).  Any questions about spatial patterns of change in a given geography, any questions about hotspots and outlier detection (??). Any questions of driver attribution given the intersection with DIST-ALERTS by referring to the final land cover class. Any questions about the accuracy of the data (validation) or the cross-dataset consistence with ESA World Cover, MODIS etc.<br>If a user asks for world area under agricultural use, Zeno should combine cropland + cultivated grassland or it should ask user to clarify which one they are interested in or if they want both combined. |
    | **Providers**<br/>Who created the data? | UMD GLAD Lab, Global Pasture Watch consortium, Land & Carbon Lab  |
    | **Citation**<br/>How should people cite this dataset? | Potapov, P., Hansen, M. C., Pickens, A., Hernandez-Serna, A., Tyukavina, A., Turubanova, S., Zalles, V., Li, X., Khan, A., Stolle, F., Harris, N., Song, X.-P., Baggett, A., Kommareddy, I. and Kommareddy, A. 2022. The global 2000–2020 land cover and land use change dataset derived from the Landsat archive: first results. – Frontiers in Remote Sensing. 3: 856903.<br>Parente, L., Sloat, L., Mesquita, V., Consoli, D., Stanimirova, R., Hengl, T., Bonannella, C., Teles, N., Wheeler, I., Hunter, M., Ehrmann, S., Ferreira, L., Mattos, A. P., Oliveira, B., Meyer, C., Şahin, M., Witjes, M., Fritz, S., Malek, Z., & Stolle, F. (2024). Annual 30-m maps of global grassland class and extent (2000–2022) based on spatiotemporal Machine Learning. Scientific Data, 11(1), 1303. https://doi.org/10.1038/s41597-024-04139-6 |
    | **Methodology** <br> How was this dataset created? | This Global Land Cover time series was created by combining annual GLAD Land Cover and Land Use Change data from the UMD GLAD lab with annual Cultivated Grassland data from the Global Pasture Watch consortium.<br>The GLAD Land Cover and Land Use Change data is a combination of separate supervised classification models for each of the major thematic classes. The models were run on Landsat Analysis Ready Data (ARD) and were calibrated locally or regionally. Each class was validated with a statistical sample analysis. The forest height, cropland, snow/ice, built-up, and water were combined with a vegetation fraction layer with a specific hierarchy in order to create the combined land cover map for each year. A wetland layer was overlaid onto the data in forest and short vegetation areas. Because of the continuous nature of the vegetation fraction, forest height, and water classes, we re-classified the values into eight classes: bare ground & sparse vegetation (<20% vegetation fraction), short vegetation (>=20% vegetation fraction <5m in height), tree cover (>=5m in height), wetland short vegetation, water (20-100% of the year), snow & ice, cropland, and built-up. Each land cover was validated separately with overall accuracies as follows: Forest extent in 2020: 97.2% (0.7 s.e.), Cropland extent in 2016-2019: 97.2%(0.3 s.e.), Snow/Ice extent in 2020: 99.8% (0.04 s.e.). There was also validation done for the changes over time for each class, available in the full paper.<br>The Cultivated Grasslands layer from Global Pasture Watch, which shows the spatiotemporal distribution of cultivated and natural/semi-natural grassland classes, was produced by using GLAD Landsat ARD-2 image archive, accompanied by climatic, landform and proximity covariates, spatiotemporal machine learning (per- class Random Forest) and over 2.3 M reference samples (visually interpreted in Very High Resolution imagery).Custom probability thresholds (based on five-fold spatial cross-validation) were used to derive dominant class maps with balanced user’s and producer’s accuracy, resulting in f1 score of 0.64 and 0.75 for cultivated and natural/semi-natural grassland, respectively.<br>The areas with a probability over 42% for natural/semi-natural grasslands and 38% for cultivated grasslands were combined into a dominant map where the natural/semi-natural class has priority.<br>Cultivated Grassland pixels from the dominant class map were isolated and inserted into the short vegetation and wetland classes in the GLAD data as an eighth class. |
    | **Cautions**<br>What should be kept in mind when using this dataset? | This dataset represents land covers and some land uses, but when calculating areas of change, it should be noted that it shows land cover change, not necessarily land use change. It also does not represent conversion, a concept defined by the Accountability Framework initiative. Caution should be used if using this land cover change data over the full time period since it does not capture all the changes in the time series, only what the pixels were in 2015 and 2024.<br>Transitions between the ‘bare ground & sparse vegetation’ and ‘short vegetation’ or ‘wetland short vegetation’ classes can be due to precipitation patterns or minor changes in vegetation cover and are not necessarily large changes in vegetation cover or degradation.<br>If a user asks about tree cover loss due to another land cover, zeno should answer with both an area of TCL due to a certain driver (TCL grouped by a specific driver) and percent of loss that was due to that driver, NOT with the land cover change areas from this product.<br>Land cover transitions to vegetation are not necessarily restoration.<br>Users should exercise caution if using this data at the local scale. We encourage ground-truthing data if using this for decision-making. Data not suitable for within year dynamics like crop cycles and flood pulses.<br>Errors of commission and omission could lead to misclassification of land cover, land use, and change. All remote sensing products contain errors and should be validated with collection of sample or ground truth data. Atmospheric and cloud noise can lead to data gaps especially in the tropics and mountainous regions.<br>Areas of land cover classes and change reported in this data is from independent remote sensing models and are not official national statistics. |
    | **Resolution** | 30 x 30 meters |
    | **Geographic Coverage** | Global land area (excluding Antarctica and other Arctic islands). |
    | **Update Frequency** | Annual |
    | **Content Date** | 2015-2024 |
    | **Keywords**<br/>A list of keyword tags related to this dataset so that the LLM better identify contexts where it is relevant. | global, land cover, land cover change, cultivated grasslands, tree cover gain, cropland expansion (or agricultural expansion), urbanization (or urban expansion), bare ground, sparse vegetation, short vegetation, grassland, shrubland, cultivated, cropland, built-up, urban, forest, tree cover, water, wetland, machine learning, annual, Landsat, time series, remote sensing, 30 m  |

    -----

    **Key Features:**
    - 🆔 Deterministic UUID generation using SHA-1 hashing (UUIDv5)
    - 💾 Automatic payload storage in temporary storage
    - 🔗 Returns a URL to check analytics status
    - ♻️ Idempotent: Identical payloads return the same resource ID

    **Flow:**
    1. Accepts `LandCoverChangeAnalyticsIn` payload
    2. Generates UUID based on payload content
    3. Stores payload as JSON file
    4. Returns resource URL for status checking
    """

create_land_cover_change.__doc__ = api_doc
create_land_cover_composition.__doc__ = api_doc
