name: Build, test on push to feature branch

on:
  push:
    branches-ignore:
      - main

env:
  CONTAINER_REPO_NAME: analytics-api

jobs:
  build_api_image:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      project_dir: 'api'

  run_api_tests:
    needs: build_api_image
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      project_dir: 'api'

  build_pipelines_image:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      project_dir: 'pipelines'

  run_pipelines_tests:
    needs: build_pipelines_image
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      project_dir: 'pipelines'
