name: Build, test on push to feature branch

on:
  push:
    branches-ignore:
      - main

env:
  CONTAINER_REPO_NAME: analytics-api

jobs:
#  build_api_image:
#    uses: ./.github/workflows/build.yml
#    secrets: inherit
#    with:
#      project_dir: 'api'
#
#  run_api_tests:
#    needs: build_api_image
#    uses: ./.github/workflows/test.yml
#    secrets:
#      AWS_REGION: ${{ secrets.AWS_REGION }}
#      AWS_GFW_ACCESS_KEY_ID: ${{ secrets.AWS_GFW_ACCESS_KEY_ID }}
#      AWS_GFW_SECRET_ACCESS_KEY: ${{ secrets.AWS_GFW_SECRET_ACCESS_KEY }}
#      AWS_ZENO_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#      AWS_ZENO_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_ZENO_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      CONTAINER_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
#      GFW_API_KEY: ${{ secrets.API_KEY }}
#      DASK_SCHEDULER_ADDRESS: ${{ secrets.DASK_SCHEDULER_ADDRESS }}
#    with:
#      project_dir: 'api'

  build_pipelines_image:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      project_dir: 'pipelines'

  run_pipelines_tests:
    needs: build_pipelines_image
    uses: ./.github/workflows/test.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_GFW_ACCESS_KEY_ID: ${{ secrets.AWS_GFW_ACCESS_KEY_ID }}
      AWS_GFW_SECRET_ACCESS_KEY: ${{ secrets.AWS_GFW_SECRET_ACCESS_KEY }}
      AWS_ZENO_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ZENO_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ZENO_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CONTAINER_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      GFW_API_KEY: ${{ secrets.API_KEY }}
      DASK_SCHEDULER_ADDRESS: ${{ secrets.DASK_SCHEDULER_ADDRESS }}
    with:
      project_dir: 'pipelines'
