name: Build and Push Docker Image to AWS ECR

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    container: "ghcr.io/osgeo/gdal:ubuntu-small-3.10.3"
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install sudo, node for later actions
        if: success()
        shell: bash
        run: |
          apt-get update
          apt-get install sudo nodejs -y

      - name: Install CLANG for building rasterio deps
        if: success()
        id: install_clang
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest

      - name: Install GCC for building rasterio deps
        if: success()
        id: install_gcc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest

      - name: Install uv, create a VENV, and enable caching
        if: success()
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
          prune-cache: false

      - name: Install project dependencies
        if: success()
        shell: bash
        env:
          CC: ${{ steps.install_clang.outputs.cc }}
          GCC: ${{ steps.install_gcc.outputs.cc }}
        run: |
          cd $GITHUB_WORKSPACE
          uv sync --locked --no-install-project --dev -p 3.13.5

      - name: Run tests
        if: success()
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pytest test --maxfail=1 --disable-warnings

##      - name: Log in to AWS ECR
##        if: success()
##        id: login-ecr
##        uses: aws-actions/amazon-ecr-login@v1

#      - name: Set up Docker, only needed if running locally
#        if: ${{ env.ACT }}
#        uses: docker/setup-docker-action@v4

#      - name: Build Docker Image
#        run: |
#          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)  # Use the first 7 characters of the commit hash as the tag
#          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG .
#          echo Image tag: $IMAGE_TAG

#      # Push the Docker image to ECR
#      - name: Push Docker Image to ECR
#        run: |
#          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
#          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG

    env:
      AWS_REGION: us-east-1  # Replace with your AWS region
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # Store your AWS account ID in GitHub Secrets
      REPOSITORY_NAME: fastapi-app  # Replace with your ECR repository name
  